services:
  app:
    build: .
    container_name: saep-app
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: saep-postgres
    env_file:
      - .env.docker
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
