spring.application.name=saep-veterinaria
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=${PORT:8080}

api.security.token.secret=${PALAVRA_SECRETA}
api.security.expiration.time=${JWT_EXPIRATION_TIME:3600}
logging.pattern.level=%5p [correlationId:%X{correlationId:-}]
