spring.application.name=saep-veterinaria

# =========================
# .ENV
# =========================
spring.config.import=optional:file:.env[.properties]

# =========================
# BANCO DE DADOS
# =========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gerar script SQL
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create

# Arquivo de saída
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=infra/create.sql

# Fonte da geração
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata

# =========================
# THYMELEAF
# =========================

spring.thymeleaf.cache=false

# =========================
# PORTA DA APLICAÇÃO
# =========================

server.port=8080