CREATE TABLE produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('RACAO','MEDICAMENTO','VACINA','INSUMO')),
    unidade_medida VARCHAR(10) CHECK (unidade_medida IN ('KG','MG','ML','UNIDADE')),
    dosagem NUMERIC(10,2),
    peso_kg NUMERIC(10,2),
    quantidade_estoque INTEGER NOT NULL CHECK (quantidade_estoque >= 0),
    estoque_minimo INTEGER NOT NULL CHECK (estoque_minimo >= 0),
    validade DATE,
    status_produto BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMINISTRADOR','FUNCIONARIO')),
    status_usuario BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT
);

CREATE TABLE movimentacao_estoque (
    id_movimentacao_estoque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade >= 1),
    tipo_movimentacao VARCHAR(20) NOT NULL CHECK (tipo_movimentacao IN ('ENTRADA','SAIDA')),
    status_movimentacao BOOLEAN DEFAULT TRUE NOT NULL,
    data_criacao_movimentacao TIMESTAMP(6),
    data_atualizacao_movimentacao TIMESTAMP(6),
    version BIGINT
);

-- =========================
-- INDEXES
-- =========================

CREATE INDEX idx_movimentacao_produto
    ON movimentacao_estoque (id_produto);

CREATE INDEX idx_movimentacao_usuario
    ON movimentacao_estoque (id_usuario);

CREATE INDEX idx_movimentacao_status
    ON movimentacao_estoque (status_movimentacao);

CREATE INDEX idx_produto_status
    ON produto (status_produto);

CREATE INDEX idx_usuario_status
    ON usuario (status_usuario);

-- =========================
-- FOREIGN KEYS
-- =========================

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT fk_movimentacao_produto
    FOREIGN KEY (id_produto)
    REFERENCES produto (id_produto);

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT fk_movimentacao_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuario (id_usuario);