CREATE TABLE IF NOT EXISTS usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status_usuario BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade_estoque INTEGER NOT NULL,
    estoque_minimo INTEGER NOT NULL,
    validade DATE,
    peso_kg DECIMAL(10, 2),
    dosagem DECIMAL(10, 2),
    unidade_medida VARCHAR(10),
    status_produto BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS movimentacao_estoque (
    id_movimentacao_estoque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    data_criacao_movimentacao TIMESTAMP,
    data_atualizacao_movimentacao TIMESTAMP,
    status_movimentacao BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_movimentacao_produto FOREIGN KEY (id_produto) REFERENCES produto (id_produto),
    CONSTRAINT fk_movimentacao_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_movimentacao_quantidade CHECK (quantidade >= 1)
);

CREATE INDEX IF NOT EXISTS idx_produto_status ON produto (status_produto);
CREATE INDEX IF NOT EXISTS idx_usuario_status ON usuario (status_usuario);
CREATE INDEX IF NOT EXISTS idx_movimentacao_status ON movimentacao_estoque (status_movimentacao);
CREATE INDEX IF NOT EXISTS idx_movimentacao_produto ON movimentacao_estoque (id_produto);
CREATE INDEX IF NOT EXISTS idx_movimentacao_usuario ON movimentacao_estoque (id_usuario);
